# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9f74956996a527656aac211e41337e0fe0bf43323f1177f1ddf00116c803b7dfd108f01513441162da85d3d3d17c0306f14076e6dbe5e116283472ef29b3455

test:
  secret_key_base: 84d015ae415c14c7292ec9edd97c7363f4bac5f6fbcba610dbf93527b925e0640cf07191d19257ec12db68a2fb9dde84eb959bad18fc0db12eaa2e0f3bdb54a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
